on: push
name: ShellCheck
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      uses: ludeeus/action-shellcheck@0.5.0
      with:
        args: azuriom-install.sh -e SC2034,SC2154